### PR TITLE
Bump outdated dependencies.

### PR DESCRIPTION
**Pull request by jmcarp**
Fixes outdated dependencies with a big red warning next to them in https://david-dm.org/18f/standup-slack-bot. Can we set up greenkeeper or similar so that a human doesn't have to do this?

### CODE REVIEW

**Comment by mgwalker** [comment]
If greenkeeper is GSA-approved, then yes please!  But I thought I'd heard at one point that it wasn't.  Maybe that has changed?  Sounds like a question for #infrastructure maybe.  Or @ctro or @mheadd, as AcqStack's infrastructure representatives.  😈

Going to hold this open until Monday when I can just double-check that everything still works against a real slack.  We're...  lacking on integration tests.  It's _probably_ fine, but I want to bang it over the head a little first.

**Review by mgwalker — APPROVED** [review]
The bot can still connect to Slack (botkit, dotenv), give help (marked), interact with the data model (sequelize) and persist and read data to the database (pg).  LGTM 🚀

**Comment by ctro** [comment]
This PR is closed already, but I'm coming here anyways to say that I haven't heard anything about greenkeeper -- if you'd like me to dig in w/ the infra folks let me know, happy to do so!

**Comment by mgwalker** [comment]
@ctro It was submitted for approval a couple of weeks ago.  We'll see what happens.  👍

**Pull request merged**
